### ISSUE TITLE
Establish code style guidelines and PR acceptance citeria

### ISSUE THREAD

**Issue by mrjf** [ecohealthalliance/mantle#8]

**Comment by dannysullivan** [comment]
Barely a style concern, but I noticed that some files in rana have extra whitespace at the ends of lines. I think it's best practice to not include that, since you can get confusing diffs if someone deletes that space in a future commit.

**Comment by dannysullivan** [comment]
Since we broke down the work into user stories, the PR acceptance criteria should be clear from the story itself (plus test coverage).

**Comment by dannysullivan** [comment]
Here's a pretty good starting point for a coffeescript style guide: https://github.com/polarmobile/coffeescript-style-guide

There are a few things I disagree with in here. I prefer to include the parentheses in definitions of methods that take no arguments (i.e.,"() ->" vs. "->").  In fact, I almost always prefer parentheses unless there's a lot of nesting going on, since I think it's harder to cause bugs when you're being explicit about your arguments.  I also prefer trailing commas (see the first code example in the guide) so that we're not relying too heavily on the layout of the code for functionality.

**Comment by mrjf** [comment]
The whitespace issue is more of a concern for me than anything else, because I remove trailing whitespace on save and sometimes this leads to merge conflicts where there really are none.

I agree on parens.

**Comment by dannysullivan** [comment]
I started a wiki and adapted that other style guide to fit what we're talking about, feel free to edit it: https://github.com/ecohealthalliance/mantle/wiki/Coffeescript-Style-Guide

**Comment by mrjf** [comment]
We could run CoffeeLint on CI or just agree to run it locally with pre-commit hooks:

http://www.coffeelint.org

It's configurable, but I haven't verified that every style we prefer is possible.

**Comment by dannysullivan** [comment]
I like that idea, provided the CI part of it is easy to set up.  Looks like everything we want is covered except for enforcing the use of empty parens in function definitions (you can enforce the absence of parens but not their presence).  That might even be something we should compromise on, since it seems like the coffeescript world as a whole doesn't like including those parens.

**Comment by mrjf** [comment]
The qualm I would have of making it part of CI is there may be times we want to allow exceptions to our own guide, and not have that block things or generate all kinds of annoying warnings. Personally, I think going > 78 characters per line is sometimes the lesser of two evils, for instance. 

But we could have a set of hard criteria, like trailing whitespace, that we would always enforce.

**Comment by dannysullivan** [comment]
Yeah I'd rather us just remove the enforcement of rules we don't always care about, and only include the ones we do.  We had a similar setup at my last job, and we pretty quickly figured out which rules were more annoying than helpful and removed them.
